config/routes.rb
Rails.application.routes.draw do
  resources :search_projects
  devise_for :users
  resources :users, only: [:show]
  resources :projects do
  	resources :projects_donations
  end


  resources :charities, only: [:show, :index] do
    resources :donations
  end

  root to: "pages#home"

  get 'user_home', to: "pages#user_home"
  get 'charity_home', to: "pages#charity_home"
  get 'ranking', to: "pages#ranking"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/projects_donations_controller.rb
class ProjectsDonationsController < ApplicationController
  before_action :set_project
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    if params[:search]
      @donations = @project.donations.search(params[:search]).order("created_at DESC")
    else
      @donations = @project.donations.all.order('created_at DESC')
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
      @donation = @project.donations.new(user: current_user)
      @name = @project.name
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = @project.donations.new(donation_params)
    respond_to do |format|
      if @donation.save
        @project.current_amount += @donation.value
        @project.save
        format.html { redirect_to project_projects_donation_path(@project, @donation), notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        byebug
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to project_donation_path(@project, @donation), notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = @project.donations.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      donation_params = params.require(:donation)
      donation_params[:user_id] = current_user.id
      donation_params[:recipient_type] = "Project"
      donation_params.permit(:user_id, :description, :value, :recipient_id,:recipient_type)
    end


end

app/views/projects_donations/_form.html.erb
<%= form_with(model: @donation, url: form_url) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :donation_description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :donation_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects_donations/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects_donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects_donations/new.html.erb
<h1>Create a new donation to <%= @name %></h1>

<%= render 'form', donation: @donation, form_url: project_projects_donations_path(@project) %>

<%= link_to 'Back', projects_path(@project) %>

app/views/projects_donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @donation.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @donation.value %>
</p>

<p>
	<strong>User ID: </strong>
	<%= @donation.user_id %>
</p>

<%= link_to 'Back', project_path(@project) %>