config/routes.rb
Rails.application.routes.draw do
  resources :search_projects
  devise_for :users
  resources :users, only: [:show]
  resources :projects do
  	resources :projects_donations
  end


  resources :charities, only: [:show, :index] do
    resources :donations
  end

  root to: "pages#home"

  get 'user_home', to: "pages#user_home"
  get 'charity_home', to: "pages#charity_home"
  get 'ranking', to: "pages#ranking"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :donations, as: :recipient
	validates :user_id, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update, :destroy]

	def new
		@project = Project.new(user_id: current_user.id)
	end

	def show
		@charity = Charity.find(@project.user_id)
	end

	def index
		if params[:term]
			@projects = Project.where("name LIKE ?", "%#{params[:term]}%")
		else
			@projects = Project.all			
		end
	end

	def edit
		@charity = Charity.find(@project.user_id)
	end

	def create
	    @project = Project.new(project_params)
	    respond_to do |format|
	      if @project.save
	        format.html { redirect_to project_path(@project), notice: 'project was successfully created.' }
	        format.json { render :show, status: :created, location: @project }
	      else
	        format.html { render :new }
	        format.json { render json: @project.errors, status: :unprocessable_entity }
	      end
    	end
    end

    def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


    private

    def set_project
    	@project = Project.find(params[:id])
    end

    def project_params
    	project_params = params.require(:project)
    	project_params[:user_id] = current_user.id
    	project_params[:current_amount] = 0
    	project_params.permit(:name, :description, :goal_amount, :project_type, :user_id, :current_amount, :urgent, :term)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, url: form_url, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name%>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label "Categoria"%>
    <%= form.select(:project_type, options_for_select([["Alimentos", "Alimentos"], ["Infraestrutura", "Infraestrutura"], ["Educação", "Educação"], ["Roupas", "Roupas"], ["Lazer", "Lazer"], ["Outro", "Outro"]])) %>
  </div>

  <div class="field">
    <%= form.label "Urgência: " %>
    <%= form.select(:urgent, options_for_select([["Alta", true], ["Baixa", false]])) %>
  </div>

  <div class="field">
    <%= form.label :goal_amount %>
    <%= form.text_field :goal_amount, id: :project_goal_amount %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editar Projeto</h1>

<%= render 'form', project: @project, form_url: project_path(@project) %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projetos</h1>

<div>
  <%= form_tag(projects_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
     <%= submit_tag 'Procurar' %>
  <% end %>
</div>
  
  



<table>
  <thead>
    <tr>
      <th>Nome do Projeto</th>
      <th>Instituição</th>
      <th>Valor Arrecadado</th>
      <th>Objetivo</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <% @charity = Charity.find(project.user_id) %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= link_to @charity.name, charity_path(@charity) %></td>
        <td><%= project.current_amount %></td>
        <td><%= project.goal_amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>Create a new project</h1>


<%= render 'form', project: @project, form_url: projects_path(@project) %>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<% if @project.urgent %>
	<h2 text-color="red">URGENTE!</h2>
<% end %>

<p>
  <strong>Nome do projeto:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @project.description %>
</p>

<p>
	<strong>Categoria:</strong>
	<%= @project.project_type %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @project.goal_amount %> R$
</p>

<p>
  <strong>Valor Arrecadado:</strong>
   <%= @project.current_amount %> R$
</p>

<p>
	<strong>Organização: </strong>
	<%= link_to @charity.name, charity_path(@charity) %>
</p>

<% if current_user.id == @charity.id %>
	<%= link_to "Editar", edit_project_path(@project) %>
<% end %>

<% unless current_user.instance_of? Charity %>
<%= link_to("Doar para este projeto", new_project_projects_donation_path(@project)) %>
<% end %>
<h1>Doações Recebidas</h1>

	<table>
	  <thead>
	    <tr>
	      <th>  Doador  </th>
	      <th>  Valor  </th>
	      <th>  Data  </th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% Donation.all.where("recipient_id LIKE ?", @project.id).each do |donation| %>
	      <tr>
	        <td><%= link_to User.find(donation.user_id).name, user_path(donation.user_id) %></td>
	        <td><%= donation.value %></td>
	        <td><%= donation.created_at.strftime("%d/%m/%Y") %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>