config/routes.rb
Rails.application.routes.draw do
  resources :search_projects
  devise_for :users
  resources :users, only: [:show]
  resources :projects do
  	resources :projects_donations
  end


  resources :charities, only: [:show, :index] do
    resources :donations
  end

  root to: "pages#home"

  get 'user_home', to: "pages#user_home"
  get 'charity_home', to: "pages#charity_home"
  get 'ranking', to: "pages#ranking"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/charity.rb
class Charity < User
	validates :cnpj, presence: true

	has_many :donations, as: :recipient

	def self.search(term)
	  where("description LIKE %?%", term)
	end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  def show
  	@charity = Charity.find(params[:id])
  	@donations = Donation.where(recipient_id: @charity.id)
  	@projects = Project.where(user_id: @charity.id)
  end

  def index
  	if params[:term]
		@charities = Charity.where("name LIKE ?", "%#{params[:term]}%")
	else
		@charities = Charity.all			
	end
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/index.html.erb
<h2>Instituições</h2>

<div>
  <%= form_tag(charities_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
     <%= submit_tag 'Procurar' %>
  <% end %>
</div>
  



<table>
  <thead>
    <tr>
      <th> Nome </th>
    </tr>
  </thead>

  <tbody>
    <% @charities.each do |charity| %>
      <tr>
        <td><%= link_to(charity.name, charity_path(charity)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/charities/show.html.erb
<h1><%= @charity.name %></h1>
<p><%= @charity.email %></p>
<p>Categoria: <%= @charity.charity_type %></p>

<h4><strong><%= link_to "Fazer Doação", new_charity_donation_path(@charity) %></strong></h4>
<h2>Projetos</h2>


<table>
  <thead>
    <tr>
      <th>  Nome </th>
      <th>  Valor Arrecadado  </th>
      <th>  Objetivo  </th>
      <th>  Data  </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to(project.name, project_path(project)) %></td>
        <td><%= project.current_amount  %> R$</td>
        <td><%= project.goal_amount  %> R$</td>
        <td><%= project.created_at.strftime("%d/%m/%Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Doações</h2>
<table>
  <thead>
    <tr>
      <th>  Doador </th>
      <th>  Valor Doado  </th>
      <th>  Data da Doação  </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @total = 0 %>
    <% @donations.each do |donation| %>
    <% @total = @total + donation.value %>
    <% @user = User.find(donation.user_id) %>
      <tr>
        <td><%= link_to @user.name, user_path(@user) %></td>
        <td><%= donation.value  %> R$</td>
        <td><%= donation.created_at.strftime("%d/%m/%Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<strong>Valor total recebido: </strong>
<%= @total  %> R$
</p>